/// Flutter icons Paw
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Paw
///      fonts:
///       - asset: fonts/Paw.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Paw {
  Paw._();

  static const _kFontFam = 'Paw';
  static const String? _kFontPkg = null;

  static const IconData paw =
      IconData(0xf1b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
